### ISSUE TITLE
socketRequestTimeout

### ISSUE THREAD

**Issue by zzparkour** [wyouflf/xUtils3#117]
下载图片时遇到的

**Comment by zzparkour** [comment]
```W/x_log:HttpRetryHandler.retryRequest(L:54): null
                                                                                                     java.net.SocketTimeoutException
                                                                                                         at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
                                                                                                         at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                                         at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
                                                                                                         at java.io.InputStream.read(InputStream.java:163)
                                                                                                         at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                                                                         at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                                                                         at libcore.io.Streams.readAsciiLine(Streams.java:201)
                                                                                                         at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
                                                                                                         at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
                                                                                                         at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
                                                                                                         at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
                                                                                                         at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:218)
                                                                                                         at org.xutils.http.loader.FileLoader.load(FileLoader.java:216)
                                                                                                         at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                                         at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                                         at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253)
                                                                                                         at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:566)```

**Comment by wyouflf** [comment]
网太慢 超时了
