### ISSUE TITLE
http请求cancel问题

### ISSUE THREAD

**Issue by cr1944** [wyouflf/xUtils3#12]
调用Cancelable的cancel后，CommonCallback.onCancelled没有调用，走到onError了

**Comment by wyouflf** [comment]
错误信息是什么?

**Comment by wyouflf** [comment]
修复了一个偶发的cancel的问题, 不知道和你遇到的问题是否一样 : https://github.com/wyouflf/xUtils3/commit/ba648c792778f56041921dd194cf22f07021c371

**Comment by cr1944** [comment]
java.net.SocketException: Socket closed
                                                                                                                  at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                                                  at libcore.io.Posix.recvfrom(Posix.java:141)
                                                                                                                  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                                                                                  at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                                                                                  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
                                                                                                                  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                                                  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
                                                                                                                  at java.io.InputStream.read(InputStream.java:162)
                                                                                                                  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                                                                                  at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                                                                                  at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
                                                                                                                  at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                                                                  at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                                  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                                  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                                                  at com.networkbench.agent.impl.instrumentation.NBSHttpURLConnectionExtension.getResponseCode(SourceFile:180)
                                                                                                                  at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:189)
                                                                                                                  at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                                                  at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                                                  at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                                                  at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:234)
                                                                                                                  at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:496)
11-19 11:20:25.140 11191-11191/com.jinxin.namibox.dev E/x_log:AbsWebViewActivity$1.onError(L:177): [upload] error
                                                                                                   java.net.SocketException: Socket closed
                                                                                                       at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                                       at libcore.io.Posix.recvfrom(Posix.java:141)
                                                                                                       at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                                                                       at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
                                                                                                       at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
                                                                                                       at java.io.InputStream.read(InputStream.java:162)
                                                                                                       at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
                                                                                                       at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
                                                                                                       at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
                                                                                                       at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                                                       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                                                       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                                       at com.networkbench.agent.impl.instrumentation.NBSHttpURLConnectionExtension.getResponseCode(SourceFile:180)
                                                                                                       at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:189)
                                                                                                       at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                                       at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                                       at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                                       at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:234)
                                                                                                       at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:496)

**Comment by cr1944** [comment]
java.net.ProtocolException: unexpected end of stream
                                                                                                       at com.android.okhttp.internal.http.HttpTransport$FixedLengthOutputStream.close(HttpTransport.java:253)
                                                                                                       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                                       at com.networkbench.agent.impl.instrumentation.NBSHttpURLConnectionExtension.getResponseCode(SourceFile:180)
                                                                                                       at org.xutils.http.request.HttpRequest.getResponseCode(HttpRequest.java:323)
                                                                                                       at org.xutils.http.HttpTask.doBackground(HttpTask.java:272)
                                                                                                       at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                       at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:18)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by cr1944** [comment]
3.0.2依然如此

**Comment by wyouflf** [comment]
谢谢反馈, 问题已修复.
