### ISSUE TITLE
运行sample项目,点击上传文件UPLOAD TEST按钮,报错,为什么

### ISSUE THREAD

**Issue by walking11** [wyouflf/xUtils3#153]
Process: org.xutils.sample, PID: 19373
                                                                   java.lang.RuntimeException: invoke method error:org.xutils.sample.HttpFragment#onTest2Click
                                                                       at org.xutils.view.EventListenerManager$DynamicHandler.invoke(EventListenerManager.java:180)
                                                                       at $Proxy4.onClick(Native Method)
                                                                       at android.view.View.performClick(View.java:4448)
                                                                       at android.view.View$PerformClick.run(View.java:18461)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at org.xutils.view.EventListenerManager$DynamicHandler.invoke(EventListenerManager.java:178)
                                                                       at $Proxy4.onClick(Native Method) 
                                                                       at android.view.View.performClick(View.java:4448) 
                                                                       at android.view.View$PerformClick.run(View.java:18461) 
                                                                       at android.os.Handler.handleCallback(Handler.java:733) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: java.io.FileNotFoundException: /sdcard/test2.jpg: open failed: ENOENT (No such file or directory)
                                                                       at libcore.io.IoBridge.open(IoBridge.java:409)
                                                                       at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                       at org.xutils.sample.HttpFragment.onTest2Click(HttpFragment.java:159)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at org.xutils.view.EventListenerManager$DynamicHandler.invoke(EventListenerManager.java:178) 
                                                                       at $Proxy4.onClick(Native Method) 
                                                                       at android.view.View.performClick(View.java:4448) 
                                                                       at android.view.View$PerformClick.run(View.java:18461) 
                                                                       at android.os.Handler.handleCallback(Handler.java:733) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                       at libcore.io.Posix.open(Native Method)
                                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                                                       at libcore.io.IoBridge.open(IoBridge.java:393)
                                                                       at java.io.FileInputStream.<init>(FileInputStream.java:78) 
                                                                       at org.xutils.sample.HttpFragment.onTest2Click(HttpFragment.java:159) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at org.xutils.view.EventListenerManager$DynamicHandler.invoke(EventListenerManager.java:178) 
                                                                       at $Proxy4.onClick(Native Method) 
                                                                       at android.view.View.performClick(View.java:4448) 
                                                                       at android.view.View$PerformClick.run(View.java:18461) 
                                                                       at android.os.Handler.handleCallback(Handler.java:733) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5072) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by wyouflf** [comment]
要上传的文件不存在啊, 例子的文件是我手机上的测试文件.
