### ISSUE TITLE
上传提示 java.net.SocketException: sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by Xuzhiwei** [wyouflf/xUtils3#162]
java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                 at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
                                                 at libcore.io.IoBridge.sendto(IoBridge.java:468)
                                                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
                                                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
                                                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
                                                 at libcore.net.http.FixedLengthOutputStream.write(FixedLengthOutputStream.java:41)
                                                 at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192)
                                                 at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180)
                                                 at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142)
                                                 at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100)
                                                 at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:201)
                                                 at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                 at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                 at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
                                                 at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253)
                                                 at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
                                                 at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
                                                 at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                 at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                 at java.lang.Thread.run(Thread.java:841)
                                              Caused by: libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                 at libcore.io.Posix.sendtoBytes(Native Method)
                                                 at libcore.io.Posix.sendto(Posix.java:155)
                                                 at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
                                                 at libcore.io.IoBridge.sendto(IoBridge.java:466)
                                                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508) 
                                                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46) 
                                                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270) 
                                                 at libcore.net.http.FixedLengthOutputStream.write(FixedLengthOutputStream.java:41) 
                                                 at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192) 
                                                 at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180) 
                                                 at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142) 
                                                 at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100) 
                                                 at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:201) 
                                                 at org.xutils.http.loader.StringLoader.load(StringLoader.java:44) 
                                                 at org.xutils.http.loader.StringLoader.load(StringLoader.java:16) 
                                                 at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76) 
                                                 at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253) 
                                                 at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607) 
                                                 at org.xutils.http.HttpTask.doBackground(HttpTask.java:306) 
                                                 at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62) 
                                                 at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21) 
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                 at java.lang.Thread.run(Thread.java:841) 

华为还有三星的手机文件上传都会出现这个问题，要怎么解决啊。我看都是在httprequest里面的
  if (contentLength < Integer.MAX_VALUE) {
                            connection.setFixedLengthStreamingMode((int) contentLength);
}
这行报错

**Comment by wyouflf** [comment]
请求参数都有什么?

**Comment by Xuzhiwei** [comment]
用setMultipart上传，文本和文件，文件是zip包，其他手机都是正常的，不过应该是4.4一下手机才会这样的

**Comment by Xuzhiwei** [comment]
W/dalvikvm: VFY: unable to resolve virtual method 35000: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V
01-27 09:38:45.620 769-1221/? E/EnterpriseContainerManager: ContainerPolicy Service is not yet ready!!!
01-27 09:38:45.620 769-1056/? W/LicenseLogService: log() is called by non admin
01-27 09:38:45.710 7020-7020/? E/FormUtil: sendto failed: EPIPE (Broken pipe)
                                           java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                               at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
                                               at libcore.io.IoBridge.sendto(IoBridge.java:468)

**Comment by wyouflf** [comment]
W/dalvikvm: VFY: unable to resolve virtual method 35000: Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (J)V
这个方法并不会被调用, 只是一个警告, 4.4以下会调用
Ljava/net/HttpURLConnection;.setFixedLengthStreamingMode (I)V

**Comment by wyouflf** [comment]
尝试3.6.7
