### ISSUE TITLE
post json 出错，请求服务端都没接收到

### ISSUE THREAD

**Issue by dalufine** [wyouflf/xUtils3#164]
请求参数如下：
```
 RequestParams params = new RequestParams(LOGIN_URL);
 params.addBodyParameter("access_token", access_token);
 params.addBodyParameter("expires_in", expires_in);
 params.addBodyParameter("ret", ret);
 params.addBodyParameter("ssid", UUID.randomUUID().toString());
 params.setAsJsonContent(true);
 x.http().post(params, new Callback.CommonCallback<String>() {}

```
log如下：
```
Bad Request code: 400, msg: Bad Request, result: <html><head><title>Apache Tomcat/6.0.44 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.44</h3></body></html>
at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:220)
at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253)
at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
```

使用postman直接提交json服务端是可以收到的。

不设置`params.setAsJsonContent(true);`服务端还可以收到get请求，设置后，服务端什么都没收到

**Comment by wyouflf** [comment]
用法没有问题, 请和服务端联调.

**Comment by dalufine** [comment]
已解决，那边用实体Bean接收就可以了，大谢。
