### ISSUE TITLE
x.image()  listView或者gridView滚动时会出现好多错误

### ISSUE THREAD

**Issue by a741762308** [wyouflf/xUtils3#165]
cancelled after request
                                                                                                     org.xutils.common.Callback$CancelledException: cancelled after request
                                                                                                         at org.xutils.http.HttpTask.doBackground(HttpTask.java:316)
                                                                                                         at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                         at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                         at java.lang.Thread.run(Thread.java:818)
01-27 17:13:01.837 27045-27129/com.jsqix.multiimgupload W/x_log:HttpRetryHandler.retryRequest(L:67): The Exception can not be retried.
01-27 17:13:01.842 27045-27064/com.jsqix.multiimgupload I/art: Background partial concurrent mark sweep GC freed 1464(76KB) AllocSpace objects, 6(2MB) LOS objects, 2% free, 134MB/138MB, paused 13.513ms total 40.562ms
01-27 17:13:01.977 27045-27185/com.jsqix.multiimgupload E/x_log:ImageDecoder.decodeBitmap(L:288): unknown bitmap configuration
                                                                                                  java.lang.IllegalArgumentException: unknown bitmap configuration
                                                                                                      at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
                                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
                                                                                                      at org.xutils.image.ImageDecoder.cut2ScaleSize(ImageDecoder.java:507)
                                                                                                      at org.xutils.image.ImageDecoder.decodeBitmap(ImageDecoder.java:259)
                                                                                                      at org.xutils.image.ImageDecoder.decodeFileWithLock(ImageDecoder.java:117)
                                                                                                      at org.xutils.image.ImageLoader.prepare(ImageLoader.java:387)
                                                                                                      at org.xutils.image.ImageLoader.prepare(ImageLoader.java:37)
                                                                                                      at org.xutils.http.HttpTask.doBackground(HttpTask.java:302)
                                                                                                      at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                      at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
忽略CancelledException之类的调试信息, 滑动时一下移出屏幕被重用的view对应的任务会自动取消.
