### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by brook19** [wyouflf/xUtils3#185]
W/x_log:HttpRetryHandler.canRetry(L:54): Request Entity Too Large
                                                                                                   </html>
                                                                                                       at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:220)
                                                                                                       at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                                       at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                                       at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
                                                                                                       at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:253)
                                                                                                       at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:607)
                                                                                                       at org.xutils.http.HttpTask.doBackground(HttpTask.java:306)
                                                                                                       at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                       at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                       at java.lang.Thread.run(Thread.java:831)
02-05 16:35:32.165 13612-16701/com.droidsky.currencytrade W/x_log:HttpRetryHandler.canRetry(L:62): The Request Method can not be retried.
02-05 16:35:32.190 13612-13612/com.droidsky.currencytrade D/x_log:TaskProxy$InternalHandler.handleMessage(L:204): Request Entity Too Large

**Comment by wyouflf** [comment]
服务端配置和你的参数的问题: http://my.oschina.net/junn/blog/147603

**Comment by luffykou** [comment]
@brook19 你好，我也遇到这个问题，请问 问题解决了吗？
