### ISSUE TITLE
网络图片加载会随机出现图片不显示问题，报decode image error错误

### ISSUE THREAD

**Issue by SimplySu** [wyouflf/xUtils3#202]
请问，用xUtils图片模块加载网络图片，第一次加载会随机显示不出来，不退出程序再次加载图片都会显示了，这个发生和什么有关呢？

D/x_log:HttpTask.doBackground(L:300)(4082): load: http://192.168.31.144:10243/WMPNSSv4/1010100410/1_Qi01MDMzOQ.jpg
D/x_log:ProcessLock.tryLockInternal(L:178)(4082): lock: /data/data/com.xxx.xxx/cache/xUtils_img/ad3422672172c4835ef3ed49537ff8be:4082
D/x_log:ProcessLock.release(L:116)(4082): released: /data/data/com.xxx.xxx/cache/xUtils_img/ad3422672172c4835ef3ed49537ff8be.tmp:4082
D/x_log:ProcessLock.release(L:116)(4082): released: /data/data/com.xxx.xxx/cache/xUtils_img/ad3422672172c4835ef3ed49537ff8be.tmp_lock:4082
D/skia(4082): --- SkImageDecoder::Factory returned null
D/skia(4082): --- SkImageDecoder::Factory returned null
W/x_log:ImageLoader.prepare(L:386)(4082): **decode image error**
W/x_log:ImageLoader.prepare(L:386)(4082): java.io.IOException: decode image error
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.image.ImageDecoder.decodeBitmap(ImageDecoder.java:245)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.image.ImageDecoder.decodeFileWithLock(ImageDecoder.java:117)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.image.ImageLoader.prepare(ImageLoader.java:375)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.image.ImageLoader.prepare(ImageLoader.java:38)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.http.HttpTask.doBackground(HttpTask.java:328)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/x_log:ImageLoader.prepare(L:386)(4082): 	at java.lang.Thread.run(Thread.java:841)
D/x_log:ProcessLock.release(L:116)(4082): released: /data/data/com.xxx.xxx/cache/xUtils_img/ad3422672172c4835ef3ed49537ff8be:4082

**Comment by SimplySu** [comment]
已查明，为引用了已经清除的缓存内容导致的错误，为自己代码的问题，关闭此issue。
