### ISSUE TITLE
泛型异常

### ISSUE THREAD

**Issue by ehaahe** [wyouflf/xUtils3#208]
报错日志如下：
D/x_log:TaskProxy$InternalHandler.handleMessage(L:204): not support callback typeT
                                                                                                  java.lang.IllegalArgumentException: not support callback typeT
                                                                                                      at org.xutils.http.loader.ObjectLoader.<init>(ObjectLoader.java:42)
                                                                                                      at org.xutils.http.loader.LoaderFactory.getLoader(LoaderFactory.java:44)
                                                                                                      at org.xutils.http.request.UriRequest.<init>(UriRequest.java:33)
                                                                                                      at org.xutils.http.request.HttpRequest.<init>(HttpRequest.java:61)
                                                                                                      at org.xutils.http.request.UriRequestFactory.getUriRequest(UriRequestFactory.java:48)
                                                                                                      at org.xutils.http.HttpTask.createNewRequest(HttpTask.java:138)
                                                                                                      at org.xutils.http.HttpTask.doBackground(HttpTask.java:198)
                                                                                                      at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                      at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
如果没有给Callback明确的泛型类型, 请使用Callback.TypedCallback.

**Comment by ehaahe** [comment]
如果使用的是fastjson，该怎么重写getLoadType方法？

**Comment by wulijie** [comment]
恩 ok

在 2016-03-01 14:29:13，"wyouflf" <notifications@github.com> 写道：


如果没有给Callback明确的泛型类型, 请使用Callback.TypedCallback.
