### ISSUE TITLE
大文件 断点下载，报错“cancelled during request”

### ISSUE THREAD

**Issue by ken132** [wyouflf/xUtils3#213]
每当我执行 Callback.Callable 的Cancelable 方法之后 ，Logcat 就会报 “cancelled during request”，而且还要隔比较久才会  update state（AbsTask.state）,请问 这个能怎么优化

**Comment by wayking** [comment]
我也想问。。。
每次cancel的时候都会
cancelled during request
                                                                                       org.xutils.common.Callback$CancelledException: cancelled during request
                                                                                           at org.xutils.http.HttpTask.doBackground(HttpTask.java:313)
                                                                                           at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                           at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                           at java.lang.Thread.run(Thread.java:841)

**Comment by wyouflf** [comment]
连接关闭需要一定的等待时间, params.setCancelFast(true), 会立即回调但连接关闭还是异步在执行.
