### ISSUE TITLE
数据库模块的使用需要默认构造器

### ISSUE THREAD

**Issue by owen8877** [wyouflf/xUtils3#271]
在使用这个框架存储数据的时候，调用了`DbManager`的成员方法`saveBindingId`，然而总是会出现如下报错：

```
Caused by: java.lang.NoSuchMethodException: <init> []
04-15 10:19:25.116 4937-4937/... W/System.err:     at java.lang.Class.getConstructorOrMethod(Class.java:423)
04-15 10:19:25.126 4937-4937/... W/System.err:     at java.lang.Class.getConstructor(Class.java:397)
```

涉及的类的代码：

```
@Table(name = "record")
public class Record {

    @Column(name = "recordId", isId = true, property = "UNIQUE")
    private int recordId;

    @Column(name = "distance")
    private int distance;

    public Record(int distance, int duration, Date date) {
        //...
    }
}
```

私下认为是由于`Record`这个自定义类中没有给出默认构造器，导致在`TableEntity.java`的`TableEntity()`方法中无法通过`this.constructor = entityType.getConstructor();`获取到`Record`类的构造方法。
**希望在sample的相关文件中加入默认构造器提醒其他使用者。**

**Comment by 247321453** [comment]
org.xutils.db.table.TableEntity的构造方法，47行  改为 this.constructor = entityType.getDeclaredConstructor();

**Comment by wyouflf** [comment]
javabean规范要求提供无参构造
