### ISSUE TITLE
加载图片报错

### ISSUE THREAD

**Issue by 7312013787** [wyouflf/xUtils3#28]
11-25 03:49:30.706 6798-6798/org.xutils.sample E/x_log:ImageLoader.onError(L:409): http://wap.baidu.com/static/img/r/image/2014-04-18/a250be0f0af4d9dd116b4bf1f37dc5c6.jpg
                                                                                   java.io.EOFException
                                                                                       at libcore.io.Streams.readAsciiLine(Streams.java:203)
                                                                                       at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
                                                                                       at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
                                                                                       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
                                                                                       at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:495)
                                                                                       at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:187)
                                                                                       at org.xutils.http.loader.FileLoader.load(FileLoader.java:212)
                                                                                       at org.xutils.http.loader.FileLoader.load(FileLoader.java:40)
                                                                                       at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                       at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:222)
                                                                                       at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:503)

**Comment by wyouflf** [comment]
请求没响应? 网络不正常吗?

**Comment by 7312013787** [comment]
没响应,网络正常但好像有些限制,用浏览器是可以打开图片的

**Comment by EngineerZhao** [comment]
加载图片  报空针
java.lang.NullPointerException
                                                                                                                    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:632)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                                                    at org.xutils.http.request.HttpRequest.getResponseCode(HttpRequest.java:306)
                                                                                                                    at org.xutils.http.HttpTask.doBackground(HttpTask.java:272)
                                                                                                                    at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:64)
                                                                                                                    at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:18)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by wyouflf** [comment]
OkHttp偶发的bug, 新系统已修复这个问题, 少数老系统容易复现.
