### ISSUE TITLE
虚拟机上下载正常，但是到了真机上就下载错误

### ISSUE THREAD

**Issue by lishuang08** [wyouflf/xUtils3#289]
RequestParams requestParams = new RequestParams(url);
requestParams.setSaveFilePath(Utils.getSDPath() + DownPathCollection.PATH_DOWN + choicelist.get(i).filename)；

x.http().get(requestParams, callback);

W/x_log:HttpRetryHandler.canRetry(L:54): cache file not foundhttp://boxpro.cn/boxpro/api/node/workspace/SpacesStore/2b3bde8f-9492-4fac-857b-67cd520c4aba/content/abc?
                                                                                     java.lang.IllegalStateException: cache file not foundhttp://boxpro.cn/boxpro/api/node/workspace/SpacesStore/2b3bde8f-9492-4fac-857b-67cd520c4aba/content/abc?
                                                                                         at org.xutils.http.loader.FileLoader.load(FileLoader.java:255)
                                                                                         at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                         at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:76)
                                                                                         at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:268)
                                                                                         at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:618)
                                                                                         at org.xutils.http.HttpTask.doBackground(HttpTask.java:309)
                                                                                         at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                         at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                                         at java.lang.Thread.run(Thread.java:856)

下载路径应该是 http://boxpro.cn/boxpro/api/node/workspace/SpacesStore/2b3bde8f-9492-4fac-857b-67cd520c4aba/content/abc  
后面应该没有 ?  这个字符 ，真机上就突然多出来了

**Comment by wyouflf** [comment]
尝试升级到新版本以解决这个问题
