### ISSUE TITLE
image load failed

### ISSUE THREAD

**Issue by godmarvin** [wyouflf/xUtils3#304]
java.io.IOException: create cache file error:http://****/Uploads/Ad/ad_1.png?
                                                                                        at org.xutils.http.loader.FileLoader.initDiskCacheFile(FileLoader.java:280)
                                                                                        at org.xutils.http.loader.FileLoader.load(FileLoader.java:182)
                                                                                        at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                        at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                        at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                        at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                        at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                        at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                        at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                        at java.lang.Thread.run(Thread.java:818)

the demo running on oneplus X , but don't load images ,(version = "3.3.22")

**Comment by langren1353** [comment]
woooooooo oneplusX
I'm using oneplus two~~ -。-

**Comment by xiaobaDev** [comment]
use **URLEncode** to encode the url ，or use** base64**，i guess the reason is the url include some character which sdk dosen‘t know

**Comment by wyouflf** [comment]
更新到新版本
