### ISSUE TITLE
下载时有几率出现HTTP 400

### ISSUE THREAD

**Issue by cg110902** [wyouflf/xUtils3#31]
同一个下载任务 点了开始下载 等一下再点停止下载  然后再点开始 有几率出来 HTTP 400
 Bad request
 code: 400, msg: Bad request, result: null

**Comment by cg110902** [comment]
E/x_log:TaskProxy$InternalHandler.handleMessage(L:205): Bad request
                                                                                                           code: 400, msg: Bad request, result: null
                                                                                                               at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:189)
                                                                                                               at org.xutils.http.loader.FileLoader.load(FileLoader.java:212)
                                                                                                               at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                                               at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                                               at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:222)
                                                                                                               at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:502)


 E/x_log:HttpRequest.sendRequest(L:194): code: 400, msg: Bad request, result: null, url: http://gdown.baidu.com/data/wisegame/3b01550409c1ed1b/QQ_300.apk
W/x_log:HttpRetryHandler.retryRequest(L:53): Bad request
                                                                                                code: 400, msg: Bad request, result: null
                                                                                                    at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:189)
                                                                                                    at org.xutils.http.loader.FileLoader.load(FileLoader.java:212)
                                                                                                    at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                                    at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                                    at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:222)
                                                                                                    at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:502)
11-27 11:06:10.275 20158-28902/dotop.myapplication W/x_log:HttpRetryHandler.retryRequest(L:66): The Exception can not be retried.

**Comment by cg110902** [comment]
然后再点一下 又可以了 也就是说有时候从暂停到继续要点2下

**Comment by wyouflf** [comment]
服务端的的限制

**Comment by zt80hou** [comment]
xutils3.1.+有没有直接下载图片的方法？之前2.6版本有一个httpUtils.download(imgUrl, saveFileName, new RequestCallBack<File>() {...},求告知
