### ISSUE TITLE
快速加载本地缓存文件会出现问题

### ISSUE THREAD

**Issue by Androidshilei** [wyouflf/xUtils3#33]
http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsQ0l4MWpTMmJCTm8/style_imagery_integration_hero1.png
                                                                                      org.xutils.ex.FileLockedException: /storage/emulated/0/Android/data/com.xhl.windowofword/cache/xUtils_img/7590aef6920e0732bf7526b5afc18c15
                                                                                          at org.xutils.cache.LruDiskCache.createDiskCacheFile(LruDiskCache.java:164)
                                                                                          at org.xutils.http.loader.FileLoader.initDiskCacheFile(FileLoader.java:263)
                                                                                          at org.xutils.http.loader.FileLoader.load(FileLoader.java:176)
                                                                                          at org.xutils.http.loader.FileLoader.load(FileLoader.java:41)
                                                                                          at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
                                                                                          at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:222)
                                                                                          at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:506)

**Comment by Androidshilei** [comment]
缓存在本地文件快速有时候读取会出现问题

**Comment by wyouflf** [comment]
这个是为了防止重复创建缓存文件, 加了锁来保护, 加载图片时会自动重试.
