### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream 

### ISSUE THREAD

**Issue by Huangzhe** [wyouflf/xUtils3#333]
APP异常崩溃之后，再请求网络返回这个错误，是什么原因，怎么解决？

D/x_log:TaskProxy$InternalHandler.handleMessage(L:204): unexpected end of stream
                                                                                                                java.net.ProtocolException: unexpected end of stream
                                                                                                                    at com.android.okhttp.internal.http.HttpTransport$FixedLengthOutputStream.close(HttpTransport.java:253)
                                                                                                                    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                                    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:160)
                                                                                                                    at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:226)
                                                                                                                    at org.xutils.http.loader.JSONObjectLoader.load(JSONObjectLoader.java:45)
                                                                                                                    at org.xutils.http.loader.JSONObjectLoader.load(JSONObjectLoader.java:17)
                                                                                                                    at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                                                    at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                                                    at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                                                    at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                                                    at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                                    at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by hanyonglu** [comment]
应该是你两次请求的URL不一样导致的，你可能在URL中加了时间戳。

**Comment by hanyonglu** [comment]
请把你两次的URL提供出来
