### ISSUE TITLE
同步请求会失败

### ISSUE THREAD

**Issue by cxbiao** [wyouflf/xUtils3#34]
示例代码
```
 RequestParams params=new RequestParams("http://www.baidu.com");

        try {
           String response= x.http().getSync(params,String.class);
            System.out.println(response);
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }
```
异步就不会！

```
 java.lang.NullPointerException
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:632)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at org.xutils.http.request.HttpRequest.getResponseCode(HttpRequest.java:307)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at org.xutils.http.HttpTask.doBackground(HttpTask.java:271)
11-28 22:17:22.738 22125-22125/org.xutils.sample W/System.err:     at org.xutils.common.task.TaskControllerImpl.startSync(TaskControllerImpl.java:63)
11-28 22:17:22.742 22125-22125/org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.requestSync(HttpManagerImpl.java:109)
11-28 22:17:22.742 22125-22125/org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.getSync(HttpManagerImpl.java:96)
```

**Comment by wyouflf** [comment]
同步的方法只能在子线程中运行, RequestParams params=new RequestParams("https://www.baidu.com"); 百度的链接换成https.
