### ISSUE TITLE
Post方法的问题，比较诡异

### ISSUE THREAD

**Issue by LanceCong** [wyouflf/xUtils3#342]
多一个参数，就不行了，405错误。
x_log:HttpRetryHandler.canRetry(L:54): Method Not Allowed
这个如何排查？用get可以，别的工具post也可以

**Comment by LanceCong** [comment]
W/x_log:HttpRetryHandler.canRetry(L:54): Method Not Allowed
                                                                                        errorCode: 405, msg: Method Not Allowed, result: 
                                                                                            at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:244)
                                                                                            at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                            at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                            at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                            at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                            at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                            at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                            at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                            at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by LanceCong** [comment]
是服务端出错，返回405.谢谢
