### ISSUE TITLE
在5.1+的手机上，无法编译加载.so文件

### ISSUE THREAD

**Issue by jingquanxie** [wyouflf/xUtils3#347]
RT，我本身有高德地图和讯飞语音，自从加了xUtils3后，初始化地图就会出现
Error: java.lang.UnsatisfiedLinkError: No implementation found for long com.autonavi.amap.mapcore.MapCore.nativeNewInstance(java.lang.String, java.lang.String) (tried Java_com_autonavi_amap_mapcore_MapCore_nativeNewInstance and Java_com_autonavi_amap_mapcore_MapCore_nativeNewInstance__Ljava_lang_String_2Ljava_lang_String_2)
                                                                                 at com.autonavi.amap.mapcore.MapCore.nativeNewInstance(Native Method)
                                                                                 at com.autonavi.amap.mapcore.MapCore.newMap(MapCore.java:83)
                                                                                 at com.amap.api.col.i.l(AMapDelegateImp.java:586)
                                                                                 at com.amap.api.col.i.<init>(AMapDelegateImp.java:322)
                                                                                 at com.amap.api.col.i.<init>(AMapDelegateImp.java:301)
                                                                                 at com.amap.api.col.j.<init>(AMapGLSurfaceView.java:27)
                                                                                 at com.amap.api.col.j.<init>(AMapGLSurfaceView.java:21)
                                                                                 at com.amap.api.col.z.onCreateView(MapFragmentDelegateImp.java:133)
                                                                                 at com.amap.api.maps.MapView.onCreate(MapView.java:135)

我反复注释打开
   x.Ext.init(this);
        x.Ext.setDebug(BuildConfig.DEBUG); // 开启debug会影响性能

最后可以确定的说，他们有冲突

**Comment by diaosidenixi** [comment]
How to deal with this problem?

**Comment by wyouflf** [comment]
升级新版，已取消这个so文件
