### ISSUE TITLE
数据库查询，插入都报异常

### ISSUE THREAD

**Issue by Laughing2015** [wyouflf/xUtils3#382]
07-27 00:40:47.711: W/System.err(3273): org.xutils.ex.DbException: <init> []
07-27 00:40:47.711: W/System.err(3273):     at org.xutils.db.table.DbBase.getTable(DbBase.java:32)
07-27 00:40:47.711: W/System.err(3273):     at org.xutils.db.DbManagerImpl.selector(DbManagerImpl.java:364)
07-27 00:40:47.711: W/System.err(3273):     at com.king.sysclearning.dao.ModularInforDao.get(ModularInforDao.java:57)
07-27 00:40:47.711: W/System.err(3273):     at com.king.sysclearning.dao.ModularInforDao.update(ModularInforDao.java:107)
07-27 00:40:47.711: W/System.err(3273):     at com.king.sysclearning.controler.ModularDownloadManager.notifyDownloadStateChanged(ModularDownloadManager.java:117)
07-27 00:40:47.711: W/System.err(3273):     at com.king.sysclearning.controler.ModularDownloadManager.download(ModularDownloadManager.java:123)
07-27 00:40:47.711: W/System.err(3273):     at com.king.sysclearning.adapter.FunctionModuleHolder$1.handleMessage(FunctionModuleHolder.java:79)
07-27 00:40:47.711: W/System.err(3273):     at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 00:40:47.711: W/System.err(3273):     at android.os.Looper.loop(Looper.java:135)
07-27 00:40:47.711: W/System.err(3273):     at android.app.ActivityThread.main(ActivityThread.java:5254)
07-27 00:40:47.711: W/System.err(3273):     at java.lang.reflect.Method.invoke(Native Method)
07-27 00:40:47.711: W/System.err(3273):     at java.lang.reflect.Method.invoke(Method.java:372)
07-27 00:40:47.711: W/System.err(3273):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-27 00:40:47.711: W/System.err(3273):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-27 00:40:47.711: W/System.err(3273): Caused by: java.lang.NoSuchMethodException: <init> []
07-27 00:40:47.711: W/System.err(3273):     at java.lang.Class.getConstructor(Class.java:531)
07-27 00:40:47.711: W/System.err(3273):     at java.lang.Class.getConstructor(Class.java:495)
07-27 00:40:47.711: W/System.err(3273):     at org.xutils.db.table.TableEntity.<init>(TableEntity.java:47)
07-27 00:40:47.711: W/System.err(3273):     at org.xutils.db.table.DbBase.getTable(DbBase.java:30)

**Comment by Laughing2015** [comment]
解决了，居然是因为bean里面没有无参构造函数
