### ISSUE TITLE
最近执行网络请求时执行onerror 报空指针

### ISSUE THREAD

**Issue by ltigers** [wyouflf/xUtils3#411]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
    at android.widget.Toast.<init>(Toast.java:101)
    at android.widget.Toast.makeText(Toast.java:258)
    at com.lovewith.lovewith.fragment.InvitationSetFragment$4.onError(SourceFile:303)
    at org.xutils.http.HttpTask.onError(SourceFile:455)
    at org.xutils.common.task.b$b.handleMessage(SourceFile:232)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:147)
    at android.app.ActivityThread.main(ActivityThread.java:5513)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by wyouflf** [comment]
业务代码问题，位置已经很明确了，自己处理下
