### ISSUE TITLE
 x.view().inject  在oppo R9 上面报错

### ISSUE THREAD

**Issue by liupeng110** [wyouflf/xUtils3#434]

**Comment by liupeng110** [comment]
I/art: Clamp target GC heap from 262MB to 256MB
10-24 11:49:05.324 24806-24806/com.jinhuizhan.xiaoyouxi I/art: Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 3% free, 246MB/256MB, paused 1.092ms total 18.928ms
10-24 11:49:05.324 24806-24806/com.jinhuizhan.xiaoyouxi E/art: Throwing OutOfMemoryError "Failed to allocate a 13990476 byte allocation with 9936632 free bytes and 9MB until OOM"
10-24 11:49:05.325 24806-24806/com.jinhuizhan.xiaoyouxi E/art: Not gen hprof when OOME
10-24 11:49:05.325 24806-24806/com.jinhuizhan.xiaoyouxi D/skia: --- allocation failed for scaled bitmap
10-24 11:49:05.331 24806-24806/com.jinhuizhan.xiaoyouxi E/x_log:ViewInjectorImpl.inject(L:86): null
                                                                                               java.lang.reflect.InvocationTargetException
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:82)
                                                                                                   at com.jinhuizhan.xiaoyouxi.activity.Activity_Base.onCreate(Activity_Base.java:27)
                                                                                                   at android.app.Activity.performCreate(Activity.java:6231)
                                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678)
                                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                   at android.os.Looper.loop(Looper.java:210)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5809)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
                                                                                                Caused by: android.view.InflateException: Binary XML file line #30: Error inflating class <unknown>
                                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                                   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                                                   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
                                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:435)
                                                                                                   at android.app.Activity.setContentView(Activity.java:2203)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                   at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:82) 
                                                                                                   at com.jinhuizhan.xiaoyouxi.activity.Activity_Base.onCreate(Activity_Base.java:27) 
                                                                                                   at android.app.Activity.performCreate(Activity.java:6231) 
                                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
                                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534) 
                                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2678) 
                                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523) 
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                   at android.os.Looper.loop(Looper.java:210) 
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5809) 
                                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) 
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879) 
                                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                                   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                                                   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:435) 
                                                                                                   at android.app.Activity.setContentView(Activity.java:2203) 
                                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                   at org.xutils.view.ViewInjectorImpl.inject(ViewInjectorImpl.java:82) 
                                                                                                   at com.jinhuizhan.xiaoyouxi.activity.Activity_Base.onCreate(Activity_Base.java:27) 
                                                                                                   at android.app.Activity.performCreate(Activity.java:6231) 
                                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)

**Comment by liupeng110** [comment]
在魅族上和小米上是没问题的  报错的at com.jinhuizhan.xiaoyouxi.activity.Activity_Base.onCreate(Activity_Base.java:27)   
只有一句 x.view().inject(this);

**Comment by wyouflf** [comment]
新版本已修复
