### ISSUE TITLE
在 service 中使用 xutils 下载功能报错

### ISSUE THREAD

**Issue by RainyZou** [wyouflf/xUtils3#453]
RequestParams params = new RequestParams(url);
                params.setCacheDirName(FileUtils.getDownloadFile().getName());
                params.setAutoRename(true);
                Callback.Cancelable cancelable = x.http().get(params, new Callback.ProgressCallback<Object>() {);

java.lang.IllegalArgumentException: not found @HttpResponse from class java.lang.Object
                                                                                          at org.xutils.http.loader.ObjectLoader.<init>(ObjectLoader.java:80)
                                                                                          at org.xutils.http.loader.LoaderFactory.getLoader(LoaderFactory.java:44)
                                                                                          at org.xutils.http.request.UriRequest.<init>(UriRequest.java:35)
                                                                                          at org.xutils.http.request.HttpRequest.<init>(HttpRequest.java:61)
                                                                                          at org.xutils.http.request.UriRequestFactory.getUriRequest(UriRequestFactory.java:48)
                                                                                          at org.xutils.http.HttpTask.createNewRequest(HttpTask.java:139)
                                                                                          at org.xutils.http.HttpTask.doBackground(HttpTask.java:199)
                                                                                          at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                          at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                                          at java.lang.Thread.run(Thread.java:856)

**Comment by wyouflf** [comment]
和在哪里使用没有关系, 看着像没添加必要的注解或混淆配置的问题.
