### ISSUE TITLE
java.io.IOException: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by ltigers** [wyouflf/xUtils3#469]
java.io.IOException: unexpected end of stream on Connection{xxx:80, proxy=DIRECT@ hostAddress=112.124.23.219 cipherSuite=none protocol=http/1.1} (recycle count=1)
com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:150)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:210)
 at org.xutils.http.request.HttpRequest.sendRequest(SourceFile:226)
 at org.xutils.http.loader.g.load(SourceFile:44)
 at org.xutils.http.loader.g.load(SourceFile:16)
 at org.xutils.http.request.UriRequest.loadResult(SourceFile:82)
at org.xutils.http.request.HttpRequest.loadResult(SourceFile:277)
 at org.xutils.http.HttpTask$a.a(SourceFile:600)
 at org.xutils.http.HttpTask.doBackground(SourceFile:305)
 at org.xutils.common.task.b$1.run(SourceFile:62)
 at org.xutils.common.task.a.run(SourceFile:21)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:833)
 Caused by: java.io.EOFException: \n not found: size=0 content=...
 at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
 	... 19 more

**Comment by Tandy0814** [comment]
偶尔会出现，不知道怎么解决

**Comment by hbzkw** [comment]
我的也是 请问有解决方案吗@wyouflf

**Comment by ChineseBoyLY** [comment]
我经常遇到，大数据收发的时候，求解

**Comment by wyouflf** [comment]
服务端超时设置等导致的
