### ISSUE TITLE
上传文件时报错，java.net.SocketException: sendto failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by icer-CHN** [wyouflf/xUtils3#499]
描述：
   使用POST，开启了multiPart，参数有两个字符串，和三个不同key的文件，分别是音频，视频，图片文件。
   目前发现是当视频文件的大小>=2.x MB时，就会报错了。

   和之前另一个issue描述的有点像，但那里也没看到解决方案。 

log：
`
I/System.out: [CDS]write is:1404/2048
I/System.out: [CDS]write exceptionCount:0
W/x_log:HttpRetryHandler.canRetry(L:54): sendto failed: EPIPE (Broken pipe)
                                                                                              java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                                              at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:612)
                                                                                              at libcore.io.IoBridge.sendto(IoBridge.java:581)
                                                                                              at java.net.PlainSocketImpl.write(PlainSocketImpl.java:520)
                                                                                              at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:43)
                                                                                              at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:272)
                                                                                              at com.android.okio.Okio$1.write(Okio.java:70)
                                                                                              at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                                              at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
                                                                                              at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
                                                                                              at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                                              at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
                                                                                              at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192)
                                                                                              at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180)
                                                                                              at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142)
                                                                                              at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100)
                                                                                              at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:219)
                                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                              at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                              at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                              at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                              at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                              at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                              at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                                           Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                                              at libcore.io.Posix.sendtoBytes(Native Method)
                                                                                              at libcore.io.Posix.sendto(Posix.java:206)
                                                                                              at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                                              at libcore.io.IoBridge.sendto(IoBridge.java:579)
                                                                                              at java.net.PlainSocketImpl.write(PlainSocketImpl.java:520) 
                                                                                              at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:43) 
                                                                                              at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:272) 
                                                                                              at com.android.okio.Okio$1.write(Okio.java:70) 
                                                                                              at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                                              at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44) 
                                                                                              at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291) 
                                                                                              at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                                              at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131) 
                                                                                              at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192) 
                                                                                              at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180) 
                                                                                              at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142) 
                                                                                              at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100) 
                                                                                              at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:219) 
                                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:44) 
                                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:16) 
                                                                                              at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82) 
                                                                                              at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277) 
                                                                                              at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600) 
                                                                                              at org.xutils.http.HttpTask.doBackground(HttpTask.java:305) 
                                                                                              at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62) 
                                                                                              at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                              at java.lang.Thread.run(Thread.java:818) 
W/x_log:HttpRetryHandler.canRetry(L:57): http://api.iusen.com/memberSkill/applyExamine
W/x_log:HttpRetryHandler.canRetry(L:58): The Max Retry times has been reached!
D/x_log:TaskProxy$InternalHandler.handleMessage(L:204): sendto failed: EPIPE (Broken pipe)
                                                                                                         java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                                                             at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:612)
                                                                                                             at libcore.io.IoBridge.sendto(IoBridge.java:581)
                                                                                                             at java.net.PlainSocketImpl.write(PlainSocketImpl.java:520)
                                                                                                             at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:43)
                                                                                                             at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:272)
                                                                                                             at com.android.okio.Okio$1.write(Okio.java:70)
                                                                                                             at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                                                             at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
                                                                                                             at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
                                                                                                             at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                                                             at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
                                                                                                             at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192)
                                                                                                             at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180)
                                                                                                             at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142)
                                                                                                             at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100)
                                                                                                             at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:219)
                                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                                             at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                                             at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                                             at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                                             at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                                             at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                             at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                                          Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                                                             at libcore.io.Posix.sendtoBytes(Native Method)
                                                                                                             at libcore.io.Posix.sendto(Posix.java:206)
                                                                                                             at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                                                             at libcore.io.IoBridge.sendto(IoBridge.java:579)
                                                                                                             at java.net.PlainSocketImpl.write(PlainSocketImpl.java:520) 
                                                                                                             at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:43) 
                                                                                                             at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:272) 
                                                                                                             at com.android.okio.Okio$1.write(Okio.java:70) 
                                                                                                             at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                                                             at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44) 
                                                                                                             at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291) 
                                                                                                             at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                                                             at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131) 
                                                                                                             at org.xutils.http.body.MultipartBody.writeStreamAndCloseIn(MultipartBody.java:192) 
                                                                                                             at org.xutils.http.body.MultipartBody.writeFile(MultipartBody.java:180) 
                                                                                                             at org.xutils.http.body.MultipartBody.writeEntry(MultipartBody.java:142) 
                                                                                                             at org.xutils.http.body.MultipartBody.writeTo(MultipartBody.java:100) 
                                                                                                             at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:219) 
                                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:44) 
                                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:16) 
                                                                                                             at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82) 
                                                                                                             at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277) 
                                                                                                             at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600) 
                                                                                                             at org.xutils.http.HttpTask.doBackground(HttpTask.java:305) 
                                                                                                             at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62) 
                                                                                                             at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21) 
                                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                                             at java.lang.Thread.run(Thread.java:818) 
W/xHttpMgr: java.net.SocketException: sendto failed: EPIPE (Broken pipe)`

**Comment by icer-CHN** [comment]
是我这边服务器的问题。
(羞
