### ISSUE TITLE
org.xutils.ex.DbException: column name is not unique (code 19)

### ISSUE THREAD

**Issue by 456838** [wyouflf/xUtils3#505]
@Table(name ="people")
public class People {

    @Column(name ="id",isId = true,autoGen = true)
    private int id ;
    @Column(name = "name",property = "UNIQUE")
    private String name ;
    @Column(name ="age",property = "UNIQUE")
    private int age ;

请问下该怎么处理这个问题呢？

**Comment by 456838** [comment]
我打印了一下生成的sql语句，不明白为什么会出现错误。

# E/aa: CREATE TABLE IF NOT EXISTS "people" ( "id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT UNIQUE,"age" INTEGER  )
E/x_log:DbManagerImpl.save(L:186): info:INSERT INTO "people" ("name","age") VALUES (?,?)
E/aa: INSERT INTO "people" ("name","age") VALUES (?,?)
E/x_log:DbManagerImpl.save(L:186): info:INSERT INTO "people" ("name","age") VALUES (?,?)
E/aa: INSERT INTO "people" ("name","age") VALUES (?,?)
W/System.err: org.xutils.ex.DbException: column name is not unique (code 19)
W/System.err:     at org.xutils.db.DbManagerImpl.execNonQuery(DbManagerImpl.java:549)
W/System.err:     at org.xutils.db.DbManagerImpl.save(DbManagerImpl.java:187)
W/System.err:     at xutilsdemo.salton.com.xutilsdemo.impl.XDbImpl.add(XDbImpl.java:42)
W/System.err:     at xutilsdemo.salton.com.xutilsdemo.impl.PeopleImpl.save(PeopleImpl.java:18)
W/System.err:     at xutilsdemo.salton.com.xutilsdemo.MainActivity.HelloClick(MainActivity.java:25)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
W/System.err:     at android.view.View.performClick(View.java:4240)
W/System.err:     at android.view.View$PerformClick.run(View.java:17721)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:730)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err:     at android.os.Looper.loop(Looper.java:137)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5103)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)

03-08 22:08:39.115 24073-24073/xutilsdemo.salton.com.xutilsdemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by 456838** [comment]
最终的解决方法：使用replace方法
