### ISSUE TITLE
 java.io.EOFException

### ISSUE THREAD

**Issue by hxkdidi** [wyouflf/xUtils3#511]
java.io.EOFException
                                                                                             at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
                                                                                             at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:175)
                                                                                             at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:616)
                                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
                                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
                                                                                             at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:169)
                                                                                             at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:226)
                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                                             at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                                             at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                                             at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                                             at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                                             at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                                             at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                             at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by wyouflf** [comment]
连接中断?

**Comment by hxkdidi** [comment]
wifi网络状况很差的场景出现

**Comment by hxkdidi** [comment]
问题已经解决
解决方案：params.addHeader("Connection", "close");//每次访问后断开当前连接，避免EOFException的出现，目前副作用不明显。
