### ISSUE TITLE
database or disk is full求解···

### ISSUE THREAD

**Issue by liaohuyu** [wyouflf/xUtils3#516]
at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:553)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at org.xutils.db.DbManagerImpl.endTransaction(DbManagerImpl.java)
	at org.xutils.db.DbManagerImpl.save(DbManagerImpl.java)
	at com.android.tutuerge.utils.CountUtils.statistic(CountUtils.java)
	                                         statisticPager(CountUtils.java)
	                                         statisticDownload(CountUtils.java)
	at com.android.tutuerge.fragment.FragmentList.setUserVisibleHint(FragmentList.java)
	at android.support.v4.app.FragmentStatePagerAdapter.setPrimaryItem(FragmentStatePagerAdapter.java)
	                                                    finishUpdate(FragmentStatePagerAdapter.java)

**Comment by wyouflf** [comment]
没空间了, 提示给用户就行了.

**Comment by liaohuyu** [comment]
错误抓不到啊~~好像是xutils操作的报的，at com.android.tutuerge.utils.CountUtils.statistic(CountUtils.java)我在这一句抓不到错误··········

**Comment by liaohuyu** [comment]
@wyouflf 错误抓不到啊~~好像是xutils操作的报的，at com.android.tutuerge.utils.CountUtils.statistic(CountUtils.java)我在这一句抓不到错误··········

**Comment by cakemajor** [comment]
不是存储空间不足的问题。难道是xutils限制了存储上限？
