### ISSUE TITLE
post程序奔溃提示空指针异常

### ISSUE THREAD

**Issue by nesger** [wyouflf/xUtils3#518]
你好，这边应用接入友盟统计。其中友盟捕获到到一个错误是这样的。
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
跟踪到代码的位置是
    Cancelable post = x.http().post(requestParams, new XUtils3Callback<String>() {

            @Override
            public void onSucces(String result) {
                bif.succesLisener(result);
            }

            @Override
            public void onError(BaseRequestError error) {
                bif.errorLisener(error);
            }
        });
这里面的onError这一行，但是这里压根没有调用到length。因此想问下作者是否是库里面有做了类似的处理呢？

**Comment by wyouflf** [comment]
并没有, 做好把错误调用栈贴出来

**Comment by nesger** [comment]
友盟上的错误提示如下。其中135就是上面的onError那行代码
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at http.BaseRequest.requestPost(BaseRequest.java:135)
	at http.protocol.OffMsg.getOffMsg(OffMsg.java:48)
	at service.HandlerService.getOffMsg(HandlerService.java:1203)
	at service.HandlerService.access$600(HandlerService.java:111)
	at service.HandlerService$4.onReceive(HandlerService.java:544)
	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by wyouflf** [comment]
这个不是xUtils的错误吧?
