### ISSUE TITLE
ANR，使用save方法时出现anr，请帮忙看一下

### ISSUE THREAD

**Issue by MatumbaMan** [wyouflf/xUtils3#520]
"main" prio=5 tid=1 TIMED_WAIT
  | group="main" sCount=1 dsCount=0 obj=0x415c9ca8 self=0x41503408
  | sysTid=21949 nice=0 sched=0/0 cgrp=apps handle=1074385236
  | state=S schedstat=( 96774762766 97929285745 323493 ) utm=5683 stm=3994 core=0
  at java.lang.Object.wait(Native Method)
  - waiting on <0x415c9d78> (a java.lang.VMThread) held by tid=1 (main)
  at java.lang.Thread.parkFor(Thread.java:1205)
  at sun.misc.Unsafe.park(Unsafe.java:325)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
  at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:670)
  at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
  at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
  at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:310)
  at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
  at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
  at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
  at org.xutils.db.DbManagerImpl.beginTransaction(DbManagerImpl.java:482)
  at org.xutils.db.DbManagerImpl.save(DbManagerImpl.java:171)

**Comment by wyouflf** [comment]
如果有并发操作, 开启特性: isWriteAheadLoggingEnabled, 见示例项目https://github.com/wyouflf/xUtils3/blob/master/sample/src/main/java/org/xutils/sample/DbFragment.java
