### ISSUE TITLE
java.lang.NoClassDefFoundError: org.xutils.http.request.UriRequestFactory

### ISSUE THREAD

**Issue by dotw** [wyouflf/xUtils3#533]
特别奇怪，之前好好的没有问题，升级到新版本就有这个奇怪的问题。由于同时升级了AS和SDK，不知道什么原因引起的。
org.xutils.http.request.UriRequestFactory 这个类找不到，为什么包里的其他类能正常加载？

```
04-14 00:30:55.547 11239-11355/com.hzqi.sango E/dalvikvm: Could not find class 'org.xutils.x$MockApplication', referenced from method org.xutils.x.app
04-14 00:30:55.547 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve new-instance 9009 (Lorg/xutils/x$MockApplication;) in Lorg/xutils/x;
04-14 00:30:55.547 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x22 at 0x001f
04-14 00:30:55.557 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.image.ImageManagerImpl.registerInstance, referenced from method org.xutils.x.image
04-14 00:30:55.557 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve static method 64796: Lorg/xutils/image/ImageManagerImpl;.registerInstance ()V
04-14 00:30:55.557 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x71 at 0x0006
04-14 00:30:55.567 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.view.ViewInjectorImpl.registerInstance, referenced from method org.xutils.x.view
04-14 00:30:55.567 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve static method 64797: Lorg/xutils/view/ViewInjectorImpl;.registerInstance ()V
04-14 00:30:55.567 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x71 at 0x0006
04-14 00:30:55.567 11239-11355/com.hzqi.sango D/dalvikvm: DexOpt: unable to opt direct call 0xfd35 at 0x21 in Lorg/xutils/x;.app
04-14 00:30:55.637 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequestFactory.getDefaultTracker, referenced from method org.xutils.http.HttpTask.<init>
04-14 00:30:55.637 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve static method 64794: Lorg/xutils/http/request/UriRequestFactory;.getDefaultTracker ()Lorg/xutils/http/app/RequestTracker;
04-14 00:30:55.637 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x71 at 0x0079
04-14 00:30:55.647 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.647 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.657 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.667 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.667 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.677 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequestFactory.getUriRequest, referenced from method org.xutils.http.HttpTask.createNewRequest
04-14 00:30:55.677 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve static method 64795: Lorg/xutils/http/request/UriRequestFactory;.getUriRequest (Lorg/xutils/http/RequestParams;Ljava/lang/reflect/Type;)Lorg/xutils/http/request/UriRequest;
04-14 00:30:55.677 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
04-14 00:30:55.687 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.697 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.getRequestUri, referenced from method org.xutils.http.HttpTask.doBackground
04-14 00:30:55.697 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64782: Lorg/xutils/http/request/UriRequest;.getRequestUri ()Ljava/lang/String;
04-14 00:30:55.697 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x0066
04-14 00:30:55.707 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.clearCacheHeader, referenced from method org.xutils.http.HttpTask.doBackground
04-14 00:30:55.707 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64773: Lorg/xutils/http/request/UriRequest;.clearCacheHeader ()V
04-14 00:30:55.707 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x0105
04-14 00:30:55.727 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.close, referenced from method org.xutils.http.HttpTask.doBackground
04-14 00:30:55.727 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64774: Lorg/xutils/http/request/UriRequest;.close ()V
04-14 00:30:55.727 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x014e
04-14 00:30:55.737 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.getResponseCode, referenced from method org.xutils.http.HttpTask.doBackground
04-14 00:30:55.737 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64783: Lorg/xutils/http/request/UriRequest;.getResponseCode ()I
04-14 00:30:55.737 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x019d
04-14 00:30:55.747 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.757 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.767 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.777 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.777 11239-11355/com.hzqi.sango E/dalvikvm: Could not find class 'org.xutils.http.request.UriRequest', referenced from method org.xutils.http.HttpTask.onUpdate
04-14 00:30:55.777 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve check-cast 9000 (Lorg/xutils/http/request/UriRequest;) in Lorg/xutils/http/HttpTask;
04-14 00:30:55.777 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x1f at 0x000e
04-14 00:30:55.787 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xutils/http/request/UriRequest;)
04-14 00:30:55.807 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.isLoading, referenced from method org.xutils.http.HttpTask.updateProgress
04-14 00:30:55.807 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64785: Lorg/xutils/http/request/UriRequest;.isLoading ()Z
04-14 00:30:55.807 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x003d
04-14 00:30:55.807 11239-11355/com.hzqi.sango I/dalvikvm: Could not find method org.xutils.http.request.UriRequest.isLoading, referenced from method org.xutils.http.HttpTask.updateProgress
04-14 00:30:55.807 11239-11355/com.hzqi.sango W/dalvikvm: VFY: unable to resolve virtual method 64785: Lorg/xutils/http/request/UriRequest;.isLoading ()Z
04-14 00:30:55.807 11239-11355/com.hzqi.sango D/dalvikvm: VFY: replacing opcode 0x6e at 0x0078
**04-14 00:30:55.827 11239-11355/com.hzqi.sango W/System.err: java.lang.NoClassDefFoundError: org.xutils.http.request.UriRequestFactory
04-14 00:30:55.827 11239-11355/com.hzqi.sango W/System.err:     at org.xutils.http.HttpTask.<init>(HttpTask.java:103)
04-14 00:30:55.827 11239-11355/com.hzqi.sango W/System.err:     at org.xutils.http.HttpManagerImpl.request(HttpManagerImpl.java:49)
04-14 00:30:55.837 11239-11355/com.hzqi.sango W/System.err:     at org.xutils.http.HttpManagerImpl.get(HttpManagerImpl.java:34)
04-14 00:30:55.837 11239-11355/com.hzqi.sango W/System.err:     at com.hzqi.sango.AndroidPlatformManager.runCheckInBackground(AndroidPlatformManager.java:195)
04-14 00:30:55.837 11239-11355/com.hzqi.sango W/System.err:     at com.hzqi.sango.screen.MainMenuScreen.show(MainMenuScreen.java:744)
04-14 00:30:55.837 11239-11355/com.hzqi.sango W/System.err:     at com.hzqi.sango.DirectedGame.setScreen(DirectedGame.java:83)
04-14 00:30:55.847 11239-11355/com.hzqi.sango W/System.err:     at com.hzqi.sango.screen.LoadingScreen$1$1.run(LoadingScreen.java:51)
04-14 00:30:55.847 11239-11355/com.hzqi.sango W/System.err:     at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:452)
04-14 00:30:55.847 11239-11355/com.hzqi.sango W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1550)
04-14 00:30:55.847 11239-11355/com.hzqi.sango W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1255)**
```

**Comment by dotw** [comment]
经过深入分析，发现是bugly导致的，并非xutils的问题。

**Comment by xincept** [comment]
我也在用Bugly，但没遇到这个问题，能详细说说吗？
