### ISSUE TITLE
debug版本使用正常，打包realease时出现这个。急。。。（网络正常的）

### ISSUE THREAD

**Issue by live17909** [wyouflf/xUtils3#545]
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): com.a.a.d: default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.h.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.<init>(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.b(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.sample.http.JsonResponseParser.parse(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.UriRequest.loadResult(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.HttpRequest.loadResult(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask$a.a(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask.doBackground(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.b$1.run(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.a.run(Unknown Source)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 10:17:21.986: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.lang.Thread.run(Thread.java:833)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): com.a.a.d: default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.h.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.<init>(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.b(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.sample.http.JsonResponseParser.parse(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.UriRequest.loadResult(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.HttpRequest.loadResult(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask$a.a(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask.doBackground(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.b$1.run(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.a.run(Unknown Source)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 10:17:22.097: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.lang.Thread.run(Thread.java:833)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): com.a.a.d: default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.h.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.<init>(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.b(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.g.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.sample.http.JsonResponseParser.parse(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.UriRequest.loadResult(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.request.HttpRequest.loadResult(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask$a.a(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.http.HttpTask.doBackground(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.b$1.run(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at org.xutils.common.task.a.run(Unknown Source)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): 	at java.lang.Thread.run(Thread.java:833)
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): https://yantangshop.cn/cfc/terminalCanteenApi.do?action=getCanteen&dataType=mobile&ecafeNotRedirect=true&deviceUuid=49d32f46-b9f0-3ed2-96b5-6cf94ff75bbc
05-11 10:17:22.411: W/x_log:HttpRetryHandler.canRetry(L:-1)(12212): The Max Retry times has been reached!
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): --&--default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): com.a.a.d: default constructor not found. class org.james.iscas.b.a$a
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.h.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.g.<init>(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.m.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.j.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.g.b(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.g.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.b.b.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at com.a.a.a.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.sample.http.JsonResponseParser.parse(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.loader.f.load(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.request.UriRequest.loadResult(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.request.HttpRequest.loadResult(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.HttpTask$a.a(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.http.HttpTask.doBackground(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.common.task.b$1.run(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at org.xutils.common.task.a.run(Unknown Source)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 10:17:22.423: I/x_log:HomeActivity$1.onError(L:-1)(12212): 	at java.lang.Thread.run(Thread.java:833)
05-11 10:17:22.428: I/gralloc(311): Free handle(0x7fa5ba8700)
05-11 10:17:22.435: I/gralloc(311): Free handle(0x7fa9ca6100)
05-11 10:17:22.437: I/x_log:HomeActivity$1.onError(L:-1)(12212): 初始化失败，请检查网络连接并重试！
05-11 10:17:22.507: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1358, h=1120, format=0x1, usage=0xb00
05-11 10:17:22.511: I/gralloc(311): Alloc handle(0x7fa5ba8000): interfmt=0x200000001, stride=1408, size=6410240, usage=0xb00
05-11 10:17:22.511: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1358, h=1120, format=0x1, usage=0xb00
05-11 10:17:22.515: I/gralloc(311): Alloc handle(0x7fa5ba8900): interfmt=0x200000001, stride=1408, size=6410240, usage=0xb00
05-11 10:17:22.515: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1358, h=1120, format=0x1, usage=0xb00
05-11 10:17:22.519: I/gralloc(311): Alloc handle(0x7fa5ba8e00): interfmt=0x200000001, stride=1408, size=6410240, usage=0xb00
05-11 10:17:22.519: I/gralloc(311): Free handle(0x7fa5ba8e00)
05-11 10:17:22.519: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1120, h=1358, format=0x1, usage=0xb00
05-11 10:17:22.523: I/gralloc(311): Alloc handle(0x7fa5ba8e00): interfmt=0x200000001, stride=1152, size=6365184, usage=0xb00
05-11 10:17:22.537: I/gralloc(311): Free handle(0x7fa5ba8900)
05-11 10:17:22.537: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1120, h=1358, format=0x1, usage=0xb00
05-11 10:17:22.541: I/gralloc(311): Alloc handle(0x7fa5ba8900): interfmt=0x200000001, stride=1152, size=6365184, usage=0xb00
05-11 10:17:22.568: I/gralloc(311): Free handle(0x7fa5ba8400)
05-11 10:17:23.521: E/WifiConfigStore(905): updateConfiguration freq=2412 BSSID=28:2c:b2:79:34:a4 RSSI=-50 "2016test"WPA_PSK
05-11 10:17:24.088: I/wpa_supplicant(1833): wlan0: HEART-BEAT-ACK: 36
05-11 10:17:24.088: I/gralloc(311): Free handle(0x7fa5ba8000)
05-11 10:17:24.088: I/gralloc(311): Alloc req: dev=0x7faf082460, w=1120, h=1358, format=0x1, usage=0xb00
05-11 10:17:24.089: W/WifiMonitor(905): couldn't identify event type - HEART-BEAT-ACK: 36
05-11 10:17:24.095: I/gralloc(311): Alloc handle(0x7fa5ba8000): interfmt=0x200000001, stride=1152, size=6365184, usage=0xb00
05-11 10:17:26.526: E/WifiConfigStore(905): updateConfiguration freq=2412 BSSID=28:2c:b2:79:34:a4 RSSI=-49 "2016test"WPA_PSK

**Comment by live17909** [comment]
好象是混淆导致出问题的。。。
