### ISSUE TITLE
小米4手机（API19）Application初始化报错

### ISSUE THREAD

**Issue by ypf168326** [wyouflf/xUtils3#557]
第一次运行安装调试时，在application执行x.Ext.init(this)，初始化xUtils报错，
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ilifeceo.yika, PID: 10159
                                                                   java.lang.NoClassDefFoundError: org.xutils.common.task.TaskControllerImpl
                                                                       at org.xutils.x$Ext.init(x.java:90)
                                                                       at com.ilifeceo.yika.app.MyApplication.onCreate(MyApplication.java:48)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5047)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nut-bin** [comment]
我也遇到这个问题了 你这个问题是否解决了？

**Comment by wyouflf** [comment]
编译器缓存问题
