### ISSUE TITLE
在子线程插入数据后报错  org.xutils.ex.DbException: <init> []

### ISSUE THREAD

**Issue by taiwandao** [wyouflf/xUtils3#561]
在子线程插入数据后报错 

`
  org.xutils.ex.DbException: <init> []
                                                                                         at org.xutils.db.table.DbBase.getTable(DbBase.java:32)
                                                                                         at org.xutils.db.DbManagerImpl.saveOrUpdate(DbManagerImpl.java:126)
                                                                                         at com.wx.xf.model.business.UserService.getProvinceList(UserService.java:460)
                                                                                         at com.wx.xf.ui.presenter.MinePresenter.getProvinceList(MinePresenter.java:172)
                                                                                         at com.wx.xf.ui.fragment.user.UserInfoFragment$3.run(UserInfoFragment.java:268)
                                                                                         at java.lang.Thread.run(Thread.java:833)
                                                                                      Caused by: java.lang.NoSuchMethodException: <init> []
                                                                                         at java.lang.Class.getConstructor(Class.java:528)
                                                                                         at java.lang.Class.getConstructor(Class.java:492)
                                                                                         at org.xutils.db.table.TableEntity.<init>(TableEntity.java:47)
                                                                                         at org.xutils.db.table.DbBase.getTable(DbBase.java:30)
                                                                                         at org.xutils.db.DbManagerImpl.saveOrUpdate(DbManagerImpl.java:126) `

以下是插入的model
`
  @Table(name = "provice_city_info")
public class ProInfo implements IPickerViewData {
    @Column(name = "id", isId = true)
    public long id;
    @Column(name = "areaCode", autoGen = false, property = "UNIQUE")
    public String areaCode;
    @Column(name = "areaName")
    public String areaName;

    @Column(name = "parentCode")
    public String parentCode;

    public ProInfo(String areaName) {
        this.areaName = areaName;
    }

    @Override
    public String getPickerViewText() {
        return areaName;
    }
}
`

**Comment by taiwandao** [comment]
其他表都是正常插入，唯独这个表

**Comment by taiwandao** [comment]
解决了，model缺少无参数构造函数的问题
