### ISSUE TITLE
SQLiteDatabase.enableWriteAheadLogging 问题

### ISSUE THREAD

**Issue by DovSnier** [wyouflf/xUtils3#563]
D/dalvikvm: VFY: dead code 0x000a-0019 in Lorg/xutils/db/DbManagerImpl;.executeUpdateDelete (Lorg/xutils/db/sqlite/SqlInfo;)I
W/dalvikvm: threadid=9: thread exiting with uncaught exception (group=0x40161560)
E/AndroidRuntime: Uncaught handler: thread Thread-10 exiting due to uncaught exception
E/Monkey: exception :java.io.FileNotFoundException: /dev/kmsg (Permission denied)
W/System.err: java.io.FileNotFoundException: /data/logcat_0.txt (Permission denied)
E/AndroidRuntime: FATAL EXCEPTION: Thread-10
                  java.lang.NoSuchMethodError: android.database.sqlite.SQLiteDatabase.enableWriteAheadLogging
                      at com.dvsnier.database.DaoConfigFactory$1.onDbOpened(DaoConfigFactory.java:34)
                      at org.xutils.db.DbManagerImpl.<init>(DbManagerImpl.java:65)
                      at org.xutils.db.DbManagerImpl.getInstance(DbManagerImpl.java:77)
                      at org.xutils.x.getDb(x.java:75)
E/AndroidRuntime: exception :java.io.FileNotFoundException: /dev/kmsg (Permission denied)
E/AndroidRuntime: exception :java.io.FileNotFoundException: /dev/kmsg (Permission denied)
W/System.err: java.io.FileNotFoundException: /data/plog.log (Permission denied)

**Comment by DovSnier** [comment]
2.3.3(api 10) 系统的上会出现这个问题

**Comment by DovSnier** [comment]
做下版本兼容性处理就好了；
` if (Build.VERSION.SDK_INT > Build.VERSION_CODES.HONEYCOMB)
                                    db.getDatabase().enableWriteAheadLogging();`
