### ISSUE TITLE
本地图片预览失败。IllegalArgumentException: The url not be support

### ISSUE THREAD

**Issue by SupernovaCooper** [wyouflf/xUtils3#577]
java.lang.IllegalArgumentException: The url not be support: /storage/emulated/0/阅图/PictureUnlock_shijue1c3ab6e42bb10b0a79bfc85f749fb6f6_16:9.pictureunlock.jpg

文件名包含冒号，导致图片无法加载，但是上传图片正常。

The url not be support: /storage/emulated/0/阅图/PictureUnlock_shijue1c3ab6e42bb10b0a79bfc85f749fb6f6_16:9.pictureunlock.jpg
                                                                                                            java.lang.IllegalArgumentException: The url not be support: /storage/emulated/0/阅图/PictureUnlock_shijue1c3ab6e42bb10b0a79bfc85f749fb6f6_16:9.pictureunlock.jpg
                                                                                                                at org.xutils.http.request.UriRequestFactory.getUriRequest(UriRequestFactory.java:52)
                                                                                                                at org.xutils.http.HttpTask.createNewRequest(HttpTask.java:139)
                                                                                                                at org.xutils.http.HttpTask.doBackground(HttpTask.java:199)
                                                                                                                at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                                                                at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                                at java.lang.Thread.run(Thread.java:818)

排查得知
    public static UriRequest getUriRequest(RequestParams params, Type loadType) throws Throwable {

        // get scheme
        String scheme = null;
        String uri = params.getUri();
        int index = uri.indexOf(":");//这个会触发bug /storage/emulated/0/阅图/PictureUnlock_shijuef23c5ee80ab4c16b6a9a026375e3154c_16:9.pictureunlock.jpg
        if (index > 0&& index <= 10) {// 加上 && index <= 10 限制前11个字符即可解决此问题，但是scheme到底应该多长，不知道。猜测11个应该够用了。但是极端情况下还是会有这个问题，治标不治本。只是这样子只能通过修改源码来解决这个问题。
            scheme = uri.substring(0, index);//截断
        } else if (uri.startsWith("/")) {
            scheme = "file";
        }

        // get UriRequest
        if (!TextUtils.isEmpty(scheme)) {
            Class<? extends UriRequest> cls = SCHEME_CLS_MAP.get(scheme);
            if (cls != null) {
                Constructor<? extends UriRequest> constructor = cls.getConstructor(RequestParams.class, Class.class);
                return constructor.newInstance(params, loadType);
            } else {
                if (scheme.startsWith("http")) {
                    return new HttpRequest(params, loadType);
                } else if (scheme.equals("assets")) {
                    return new AssetsRequest(params, loadType);
                } else if (scheme.equals("file")) {
                    return new LocalFileRequest(params, loadType);
                } else {
                    throw new IllegalArgumentException("The url not be support: " + uri);
                }
            }
        } else {
            throw new IllegalArgumentException("The url not be support: " + uri);
        }
    }

大佬想个完美的办法吧~

**Comment by wyouflf** [comment]
文件路径前面添加 file://
