### ISSUE TITLE
上传文件  HTTP 400 Bad Request

### ISSUE THREAD

**Issue by DonaldGuo** [wyouflf/xUtils3#59]
当参数里只有一个文件时, 可以通过http解析, 当时只要添加任何一个字符串参数时必然报错

Android端上传文件代码:

	public void postFile(String url, Map<String, Object> paramsMap)  {
		RequestParams params = new RequestParams(url);
		params.setMultipart(true);
		for (String key : paramsMap.keySet()) {
			Object object = paramsMap.get(key);
			params.addParameter(key, object);
		}
		x.http().post(params, new Callback.ProgressCallback<String>() {
			@Override
			public void onSuccess(String result) {
			}

			@Override
			public void onError(Throwable ex, boolean isOnCallback) {
			}

			@Override
			public void onCancelled(CancelledException cex) {
			}

			@Override
			public void onFinished() {
			}

			@Override
			public void onWaiting() {
			}

			@Override
			public void onStarted() {
			}

			@Override
			public void onLoading(long total, long current, boolean isDownloading) {
			}
		});
	}

客户端收到的错误信息:
{"code":500,"data":{},"error":"HTTP 400 Bad Request:java.lang.IllegalArgumentException: Error parsing media type 'text/plain; charset:UTF-8'"}

服务器端解析http协议的框架是Jersey RESTful

从服务器找到有用的报错log信息:
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
Caused by: java.lang.IllegalArgumentException: Error parsing media type 'text/plain; charset:UTF-8'
Caused by: java.text.ParseException: Expected separator '=' instead of ':'

服务器端报错log(完整): 
javax.ws.rs.BadRequestException: HTTP 400 Bad Request
        at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:243) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:89) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:179) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:91) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:251) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:229) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:72) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:149) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:783) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:233) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider.getEntity(FormDataParamValueFactoryProvider.java:369) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider.access$000(FormDataParamValueFactoryProvider.java:86) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$FormDataParamValueFactory.provide(FormDataParamValueFactoryProvider.java:201) ~[jersey-media-multipart-2.9.jar:na]
        at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:81) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:121) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269) ~[jersey-server-2.9.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297) [jersey-common-2.9.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:252) [jersey-server-2.9.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1025) [jersey-server-2.9.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372) [jersey-container-servlet-core-2.9.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382) [jersey-container-servlet-core-2.9.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:345) [jersey-container-servlet-core-2.9.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:220) [jersey-container-servlet-core-2.9.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821) [jetty-servlet-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.webapp.logging.ContextLogHandler.handle(ContextLogHandler.java:62) [jetty-webapp-logging-9.0.0.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [jetty-io-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.5.v20151012.jar:9.3.5.v20151012]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.5.v20151012.jar:9.3.5.v20151012]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Error parsing media type 'text/plain; charset:UTF-8'
        at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:92) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:60) ~[jersey-common-2.9.jar:na]
        at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179) ~[javax.ws.rs-api-2.0.jar:2.0]
        at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:239) ~[jersey-media-multipart-2.9.jar:na]
        ... 61 common frames omitted
Caused by: java.text.ParseException: Expected separator '=' instead of ':'
        at org.glassfish.jersey.message.internal.HttpHeaderReader.nextSeparator(HttpHeaderReader.java:115) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.HttpHeaderReader.readParameters(HttpHeaderReader.java:261) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.HttpHeaderReader.readParameters(HttpHeaderReader.java:242) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.MediaTypeProvider.valueOf(MediaTypeProvider.java:110) ~[jersey-common-2.9.jar:na]
        at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:90) ~[jersey-common-2.9.jar:na]
        ... 64 common frames omitted

**Comment by DonaldGuo** [comment]
问题解决了, 
往RequestParams传入参数的地方改为:

	for (String key : paramsMap.keySet()) {
		Object object = paramsMap.get(key);
		if (object instanceof File) {
			params.addBodyParameter(key, (File) object);
		}else if (object instanceof String ) {
			params.addBodyParameter(key, (String) object, "application/octet-stream");
		}
	}

就上传成功了.

所以我猜想是不是body parameter 参数类型为String的时候xutils错误的指定了参数的Content-Type为"text/plain; charset:UTF-8",  然后这个charset后的冒号引发了错误, 当人为指定了application/octet-stream之后, 这个冒号错误就没有出现了

**Comment by DonaldGuo** [comment]
刚刚看了源码, org.xutils.http.body.MultipartBody里的213行的方法:

    private static byte[] buildContentType(Object value, String contentType, String charset) throws UnsupportedEncodingException {
        StringBuilder result = new StringBuilder("Content-Type: ");
        if (TextUtils.isEmpty(contentType)) {
            if (value instanceof String) {
                contentType = "text/plain; charset:" + charset;
            } else {
                contentType = "application/octet-stream";
            }
        } else {
            contentType = contentType.replaceFirst("\\/jpg$", "/jpeg");
        }
        result.append(contentType);
        return result.toString().getBytes(charset);
    }

指定了当value是String时指定 contentType = "text/plain; charset:" + charset;
charset都是用=指定的, 这里用了冒号所以服务器报错了

**Comment by DonaldGuo** [comment]
我已经提交了修改分支

**Comment by wyouflf** [comment]
谢谢反馈
