### ISSUE TITLE
database is locked (Sqlite code 5)如何解决

### ISSUE THREAD

**Issue by yuanshuaiding** [wyouflf/xUtils3#595]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.stub.StubApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 11:Try again)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5677)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 11:Try again)
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:910)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:655)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:341)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:315)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:225)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:203)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:511)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:767)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:739)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:724)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
       at org.xutils.db.DbManagerImpl.openOrCreateDatabase(DbManagerImpl.java:413)
       at org.xutils.db.DbManagerImpl.<init>(DbManagerImpl.java:62)
       at org.xutils.db.DbManagerImpl.getInstance(DbManagerImpl.java:77)
       at org.xutils.x.getDb(x.java:75)

**Comment by mytaihong** [comment]
你好  我也遇到这个问题   问题解决了吗？  解决了提供下方法 谢谢

**Comment by wyouflf** [comment]
有多个线程或进程(后台服务)同时在访问数据库?

**Comment by wyouflf** [comment]
/**
     * 关闭数据库,
     * xUtils对同一个库的链接是单实例的, 一般不需要关闭它.
     *
     * @throws IOException
     */
    void close() throws IOException;
