### ISSUE TITLE
Android 6.0 以上 网络请求时数据库报错

### ISSUE THREAD

**Issue by pardonhan** [wyouflf/xUtils3#608]
```
SQLiteDatabase: Open database
 java.lang.Throwable: stacktrace
   at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:815)
   at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
   at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:687)
   at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:672)
   at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
   at org.xutils.db.DbManagerImpl.openOrCreateDatabase(DbManagerImpl.java:413)
   at org.xutils.db.DbManagerImpl.<init>(DbManagerImpl.java:62)
   at org.xutils.db.DbManagerImpl.getInstance(DbManagerImpl.java:77)
   at org.xutils.x.getDb(x.java:75)
   at org.xutils.http.cookie.DbCookieStore.<init>(DbCookieStore.java:37)
   at org.xutils.http.cookie.DbCookieStore.<clinit>(DbCookieStore.java:27)
   at org.xutils.http.request.HttpRequest.<clinit>(HttpRequest.java:57)
   at org.xutils.http.request.UriRequestFactory.getUriRequest(UriRequestFactory.java:48)
   at org.xutils.http.HttpTask.createNewRequest(HttpTask.java:139)
   at org.xutils.http.HttpTask.doBackground(HttpTask.java:199)
   at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
   at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
   at java.lang.Thread.run(Thread.java:761)
```

**Comment by wyouflf** [comment]
未复现此问题, 试试新版本
