### ISSUE TITLE
xUtils3中关闭数据库是线程安全的吗？

### ISSUE THREAD

**Issue by zhiyong926** [wyouflf/xUtils3#611]
有时会收到这样的错误：attempt to re-open an already-closed object: SQLiteDatabase，我的调用方法如下：
DbManager db = x.getDb(MyApplication.getInstance().getDaoConfig());
![image](https://user-images.githubusercontent.com/11780271/33513380-857a0568-d77c-11e7-974d-fbc5edd380a0.png)
关于close的调用问题下面这个链接有具体描述方法
http://blog.csdn.net/dingsai88/article/details/41676373
可问题是如何适用于当前的xutils3 ?

**Comment by hitourlee** [comment]
我也收到同样的问题，有时还会有如下问题，不知是否有解决方法
`android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at org.xutils.db.DbManagerImpl.endTransaction(DbManagerImpl.java:495)
	at org.xutils.db.DbManagerImpl.save(DbManagerImpl.java:189)`

**Comment by wyouflf** [comment]
建议不要调用close方法, 进程退出会自动回收资源

**Comment by wyouflf** [comment]
/**
     * 关闭数据库,
     * xUtils对同一个库的链接是单实例的, 一般不需要关闭它.
     *
     * @throws IOException
     */
    void close() throws IOException;
