### ISSUE TITLE
ssl https 请求 出现问题 求大佬

### ISSUE THREAD

**Issue by yang-mr** [wyouflf/xUtils3#622]
boxserver E/Jetty: handle failed
                                                           java.lang.NullPointerException: ssl == null
                                                               at com.android.org.conscrypt.NativeCrypto.SSL_read_BIO(Native Method)
                                                               at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:477)
                                                               at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1014)
                                                               at org.eclipse.jetty.io.nio.SslConnection.unwrap(SslConnection.java:524)
                                                               at org.eclipse.jetty.io.nio.SslConnection.process(SslConnection.java:359)
                                                               at org.eclipse.jetty.io.nio.SslConnection.access$900(SslConnection.java:48)
                                                               at org.eclipse.jetty.io.nio.SslConnection$SslEndPoint.fill(SslConnection.java:666)
                                                               at org.eclipse.jetty.http.HttpParser.fill(HttpParser.java:1040)
                                                               at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:280)
                                                               at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
                                                               at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
                                                               at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
                                                               at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
                                                               at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
                                                               at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
                                                               at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by yang-mr** [comment]
服务器后台报的错，
我看下面的连接，里面的说是因为ssl请求完成之后，没有及时关闭socket，才导致异常。

麻烦大佬帮忙看一下。谢谢啦！！！
https://stackoverflow.com/questions/40301426/jetty-websockets-ssl-null-error/40301878#40301878
