### ISSUE TITLE
header字符串编码问题

### ISSUE THREAD

**Issue by liuhaitao1989** [wyouflf/xUtils3#664]
params.addHeader("token", convertToken());

    /**
     * 生成token
     *
     * @return
     */
    private static String convertToken() {
        String inStr = "TMkjzz333GJsoft" + new Date().getTime();
        char[] a = inStr.toCharArray();
        for (int i = 0; i < a.length; i++) {
            a[i] = (char) (a[i] ^ 'u');
        }
        return new String(a) + "a1";
    }

就会出现如下错误信息，接口校验规则暂时没法修改，请问有什么好的而解决方案：
 W/x_log:HttpRetryHandler.canRetry(L:54): Unexpected char 0x1e at 2 in header value: !8FFF2?D@@FGGCMFDMAFa1
                                                                          java.lang.IllegalArgumentException: Unexpected char 0x1e at 2 in header value: !8FFF2?D@@FGGCMFDMAFa1
                                                                              at com.android.okhttp.Headers$Builder.checkNameAndValue(Headers.java:314)
                                                                              at com.android.okhttp.Headers$Builder.add(Headers.java:245)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.addRequestProperty(HttpURLConnectionImpl.java:596)
                                                                              at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.addRequestProperty(DelegatingHttpsURLConnection.java:186)
                                                                              at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.addRequestProperty(Unknown Source:0)
                                                                              at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:170)
                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
                                                                              at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
                                                                              at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:82)
                                                                              at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:277)
                                                                              at org.xutils.http.HttpTask$RequestWorker.request(HttpTask.java:600)
                                                                              at org.xutils.http.HttpTask.doBackground(HttpTask.java:305)
                                                                              at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62)
                                                                              at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                              at java.lang.Thread.run(Thread.java:784)

**Comment by wyouflf** [comment]
你这样生成出来的字符会有不在字符集的内容
