### ISSUE TITLE
混淆后x.image().bind加载网络图片出错

### ISSUE THREAD

**Issue by ldy0909061** [wyouflf/xUtils3#71]
像下面这样的代码，混淆后无法加载图片且抛出异常，混淆前没有问题
ImageOptions imgOpt = new ImageOptions.Builder()
                .setSize(120, 120)  
                .setCrop(true)  
                .build();
        try {
            x.image().bind(timg, imageUrl, imgOpt);
        } catch (Exception e) {
            e.printStackTrace();
        }

抛出的异常如下：
 D/x_log:TaskProxy$InternalHandler.handleMessage(L:-1)﹕ FindGenericType:class org.xutils.image.ImageLoader, declaredClass: interface org.xutils.common.Callback$PrepareCallback, index: 0
    java.lang.IllegalArgumentException: FindGenericType:class org.xutils.image.ImageLoader, declaredClass: interface org.xutils.common.Callback$PrepareCallback, index: 0
            at org.xutils.common.util.ParameterizedTypeUtil.getParameterizedType(Unknown Source)
            at org.xutils.http.HttpTask.initRequest(Unknown Source)
            at org.xutils.http.HttpTask.doBackground(Unknown Source)
            at org.xutils.common.task.TaskProxy$1.run(Unknown Source)
            at org.xutils.common.task.PriorityRunnable.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
12-16 12:19:38.841  20148-20148 E/x_log:ImageLoader.onError(L:-1)﹕ http://192.168.1.31/expression/我看好你噢.jpg
    java.lang.IllegalArgumentException: FindGenericType:class org.xutils.image.ImageLoader, declaredClass: interface org.xutils.common.Callback$PrepareCallback, index: 0
            at org.xutils.common.util.ParameterizedTypeUtil.getParameterizedType(Unknown Source)
            at org.xutils.http.HttpTask.initRequest(Unknown Source)
            at org.xutils.http.HttpTask.doBackground(Unknown Source)
            at org.xutils.common.task.TaskProxy$1.run(Unknown Source)
            at org.xutils.common.task.PriorityRunnable.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by wyouflf** [comment]
参考sample项目的混淆配置:

################### region for xUtils
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,*Annotation*,Synthetic,EnclosingMethod

-keep public class org.xutils.** {
    public protected *;
}
-keep public interface org.xutils.** {
    public protected *;
}
-keepclassmembers class * extends org.xutils.** {
    public protected *;
}
-keepclassmembers class * extends org.xutils.http.RequestParams {*;}
-keepclassmembers class * {
   void *(android.view.View);
   *** *Click(...);
   *** *Event(...);
}
#################### end region

其中: -keepattributes Signature 是用来保护泛型参数的.

**Comment by ldy0909061** [comment]
非常感谢

**Comment by 247321453** [comment]
泛型T的混淆要加下面
-keepattributes Signature,EnclosingMethod

**Comment by ypf168326** [comment]
按照楼主的混淆配置文件，打包的时候报这个错：

Warning:Exception while processing task java.io.IOException: proguard.ParseException: Expecting java type before ';' in line 35 of file 

在35行执行的是这个加粗代码：
-keep public class org.xutils.** {
## public protected;
}
