### ISSUE TITLE
POST 传数组的时候 报错

### ISSUE THREAD

**Issue by lucf1103** [wyouflf/xUtils3#746]
传参是：key,Value ,Value 是自定义的List<Bean>

使用3.9.0版本，看源码是走到了 这里，没问题：

if (value instanceof Iterable) {
                for (Object item : (Iterable) value) {
                    this.bodyParams.add(new ArrayItem(name, item));
                }
            }

后续 有个转换JSON，递归发生了OOM：
at org.xutils.http.RequestParamsHelper.parseJSONObject(RequestParamsHelper.java:98)
                                                                                                    	at org.xutils.http.RequestParamsHelper$1.onParseKV(RequestParamsHelper.java:102)
                                                                                                    	at org.xutils.http.RequestParamsHelper.parseKV(RequestParamsHelper.java:51)

有人知道怎么解决吗？ list 可以 to JsonString ，但那样后台就接收不到了...
尝试了 toArray ，一样到最后会发上上面的错

**Comment by lucf1103** [comment]
params.addBodyParameter(entry.getKey(),entry.getValue());
用的这个方法，Value 是自定义的数组对象
