### ISSUE TITLE
同步请求如何实现？

### ISSUE THREAD

**Issue by JackeShen** [wyouflf/xUtils3#79]
测试代码如下:
```
@Event(value = R.id.btn_test6)
    private void onTest6Click(View view) throws  Throwable{
       new Thread(){
        @Override
        public void run() {
                RequestParams params = new RequestParams("https://www.baid.com/s");
                params.setSslSocketFactory(new DefaultParamsBuilder().getSSLSocketFactory());
                params.addBodyParameter("wd","xUtils");
                String string = null;
                try {
                    string = (String) x.http().getSync(params, Class.forName("java.lang.String"));
                    Log.d("TAG",string);
                }catch (Throwable throwable){
                    throwable.printStackTrace();
                }
            }
        }.start();
    }
```
报出错误如下:
```
org.xutils.sample W/System.err: </html>
org.xutils.sample W/System.err:     at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:214)
org.xutils.sample W/System.err:     at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
org.xutils.sample W/System.err:     at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
org.xutils.sample W/System.err:     at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
org.xutils.sample W/System.err:     at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:247)
org.xutils.sample W/System.err:     at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:513)
org.xutils.sample W/System.err:     at org.xutils.http.HttpTask.doBackground(HttpTask.java:238)
org.xutils.sample W/System.err:     at org.xutils.common.task.TaskControllerImpl.startSync(TaskControllerImpl.java:63)
org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.requestSync(HttpManagerImpl.java:99)
org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.getSync(HttpManagerImpl.java:86)
org.xutils.sample W/System.err:     at org.xutils.sample.HttpFragment$4.run(HttpFragment.java:290)
org.xutils.sample W/System.err:     at android.view.View.performClick(View.java:4336)
org.xutils.sample W/System.err:     at android.view.View$PerformClick.run(View.java:17853)
org.xutils.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:800)
org.xutils.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
org.xutils.sample W/System.err:     at android.os.Looper.loop(Looper.java:194)
org.xutils.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5469)
org.xutils.sample W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
org.xutils.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
org.xutils.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:857)
org.xutils.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
org.xutils.sample W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

若不使用新的线程则报出错误如下:
```
org.xutils.sample W/System.err: java.lang.NullPointerException
org.xutils.sample W/System.err:     at libcore.net.http.HttpEngine.writeRequestHeaders(HttpEngine.java:659)
org.xutils.sample W/System.err:     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:808)
org.xutils.sample W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:293)
org.xutils.sample W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:505)
org.xutils.sample W/System.err:     at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
org.xutils.sample W/System.err:     at org.xutils.http.request.HttpRequest.sendRequest(HttpRequest.java:212)
org.xutils.sample W/System.err:     at org.xutils.http.loader.StringLoader.load(StringLoader.java:44)
org.xutils.sample W/System.err:     at org.xutils.http.loader.StringLoader.load(StringLoader.java:16)
org.xutils.sample W/System.err:     at org.xutils.http.request.UriRequest.loadResult(UriRequest.java:81)
org.xutils.sample W/System.err:     at org.xutils.http.request.HttpRequest.loadResult(HttpRequest.java:247)
org.xutils.sample W/System.err:     at org.xutils.http.HttpTask$RequestWorker.run(HttpTask.java:513)
org.xutils.sample W/System.err:     at org.xutils.http.HttpTask.doBackground(HttpTask.java:238)
org.xutils.sample W/System.err:     at org.xutils.common.task.TaskControllerImpl.startSync(TaskControllerImpl.java:63)
org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.requestSync(HttpManagerImpl.java:99)
org.xutils.sample W/System.err:     at org.xutils.http.HttpManagerImpl.getSync(HttpManagerImpl.java:86)
org.xutils.sample W/System.err:     at org.xutils.sample.HttpFragment.onTest6Click(HttpFragment.java:290)
org.xutils.sample W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
org.xutils.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
org.xutils.sample W/System.err:     at org.xutils.view.EventListenerManager$DynamicHandler.invoke(EventListenerManager.java:173)
org.xutils.sample W/System.err:     at $Proxy5.onClick(Native Method)
```

功力很浅，求指教。

**Comment by wyouflf** [comment]
在非UI线程执行:
String result = x.http().getSync(params, String.class);

**Comment by JackeShen** [comment]
明白了，今天弄成功了。谢谢。
